---

# - name: Do Install Docker compose
#   cached_get_url:
#     cached: "{{ resource_cache }}/{{ param_conf.file }}"
#     url: "{{ param_conf.url }}"
#     dest: /usr/local/bin/docker-compose
#     mode: 0755

- name: Do Install Docker compose
  pip:
    name: docker-compose